FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -i https://mirrors.aliyun.com/pypi/simple -r requirements.txt

COPY . .

EXPOSE 8501

# streamlit允许外网访问，绑定0.0.0.0
CMD ["streamlit", "run", "app.py", "--server.address=0.0.0.0", "--server.port=8501"]